---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url: ''
sections: 
upload_dir: uploads
public_path: "{{ site.base_url }}/body"
front_matter_path: "{{ site.base_url }}/fm"
use_front_matter_path: true
file_template: ":filename:"
version: 0.38.1
