---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url: ''
sections: 
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
