---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url: ''
sections: 
upload_dir: uploads
public_path: uploads
body_path: body
use_body_path: true
file_template: ":filename:"
upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
version: 0.38.1
